[redis]
redis_host = "127.0.0.1:6380"
redis_auth = "3.1415926525Aa"
redis_prefix = "blog_"
redis_database = 0
token_key = ""

[es]
es_host = ""

[database]
db_host = "127.0.0.1"
db_port = "3306"
db_user = "root"
db_password = "root"
db_database = "study-blog"
db_timeout = "10"
db_max_conn = "10"
db_charset = "utf8mb4"